<a href="https://colab.research.google.com/github/Mansi1321/davis_training/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
numbers=np.array([20,30,40,70])
print(numbers)

[20 30 40 70]


In [9]:
import numpy as np
x=np.arange(10,100,5)
print(x)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [13]:
#array creation in numpy
array3=np.zeros([3,5])
print(array3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
array4=np.zeros((4,5),dtype='int')
print(array4)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
