<a href="https://colab.research.google.com/github/Mansi1321/davis_training/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#ones array
array5=np.ones((4,3))
print(array5)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [2]:
import numpy as np
#ones array
array4=np.ones((3,5,1))
print(array4)


[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]]


In [5]:
n=int(input("enter a number:"))
array=np.arange(1,n+1)
factors=array[n%array==0]
evenfactors=factors[factors%2==0]
print("even factors are",evenfactors)

enter a number:32
even factors are [ 2  4  8 16 32]
